### ISSUE TITLE
Bug on click Player Menu Item 

### ISSUE THREAD

**Issue by Trayz99** [IT-KiLLER/CSGO-JailBreak-Last-Request-LEADERBOARD#1]
Hello, i enjoyed your plugin but has a problem,
When I click on player menu item , dont show the stats from the players.
I think it´s this line causing the issue: https://github.com/IT-KiLLER/CSGO-JailBreak-Last-Request-LEADERBOARD/blob/master/LR_LEADERBORAD.sp#L226

**Comment by IT-KiLLER** [comment]
Hi,
Thank you for reporting.
I am not aware of the problem and can not reproduce the error.

Still have trouble? Can you try to describe more? Screenshots?

sorry for late answer.

**Comment by IT-KiLLER** [comment]
I close this because of inactivity.
Feel free to report problems
